<div class="nav-scroller bg-white box-shadow fixed-top">
    <nav class="nav nav-underline">
        <a class="nav-link active" href="/documentacao"><strong>Documentação</strong></a>
        <a class="nav-link" href="#"><i class="fas fa-code-branch"></i> Downloads <span style="color: #FFF;" class="badge badge-pill bg-danger align-text-bottom"><?= $downloads ?></span></a>
        <a class="nav-link" href="/documentacao/rotas"><i class="fas fa-route"></i> Rotas</a>
        <a class="nav-link" href="/documentacao/injecao-de-dependencia"><i class="fas fa-syringe"></i> Injeção de Depedência</a>
        <a class="nav-link" href="/documentacao/controller"><i class="fas fa-gamepad"></i> Controller</a>
        <a class="nav-link" href="/"><i class="far fa-eye"></i> Layout/Views</a>
        <a class="nav-link" href="/"><i class="fas fa-university"></i> Banco de dados</a>
        <a class="nav-link" href="/"><i class="fas fa-server"></i> Servidor</a>
        <a class="nav-link" href="/"><i class="fab fa-codepen"></i> Componentes</a>
    </nav>
</div>

<div class="header-index">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <figure>
                    <img src="/assets/img/worksena-min.png" class="img-fluid logo-home" alt="">
                </figure>
                <h2 class="text-center"><?= $version ?></h2>
                <h4 class="text-justify">
                    WorkSena é um micro framework PHP, desenvolvido com o objetivo de facilitar o processo de desenvolvimento de aplicações web,utilizando padrões de projetos especializados em performance de alto desenvolvimento na web.
                </h4>
                <p class="text-center">
                    <button class="btn btn-danger btn-lg"><i class="fas fa-external-link-alt"></i> Vamos lá</button>
                </p>
            </div>
        </div>
    </div>
</div>
