<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="/assets/css/bar.css">
<link rel="stylesheet" href="/assets/css/prism.css">

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header"></div>
        <ul class="list-unstyled components">
            <p class="text-center">Documentação</p>
            <li>
                <a href="/documentacao">Instalação</a>
            </li>
            <li>
                <a href="/documentacao/modulo">Modulos</a>
            </li>
            <li>
                <a href="/documentacao/rotas">Rotas</a>
            </li>
            <li class="active">
                <a href="/documentacao/controller">Controller</a>
            </li>
            <li>
                <a href="/documentacao/injecao-de-dependencia">Injeção de Dependência</a>
            </li>
            <li>
                <a href="/documentacao/views">Views</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Componentes</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Worksena-Authetication</a>
                    </li>
                    <li>
                        <a href="#">Worksena-orm</a>
                    </li>
                    <li>
                        <a href="#">Worksena-validator</a>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="https://github.com/WalderlanSena/worksena" target="_blank" class="download"><i class="fab fa-github-alt"></i> Código fonte</a>
            </li>
            <li>
                <a href="https://pag.ae/bfr49JT" target="_blank" class="article"><i class="fas fa-hand-holding-usd"></i> Fazer uma Doação</a>
            </li>
        </ul>
        <p class="text-center"><strong>License - </strong> MIT</p>
        <p class="text-center cita">"A vida não te paga pelo que você sabe, e sim pelo que leva as pessoas a fazerem com que o você sabe!"</p>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <p class="text-lg-right">
            <button class="btn btn-sm btn-outline-danger mr-5" id="sidebarCollapse"><i class="fas fa-bars"></i> Documentação Menu</button>
        </p>

        <h1 class="text-danger"><i class="fab fa-codepen"></i> Controller</h1>
        <div class="line"></div>

        <h4 id="instalacao">Criando um novo controller</h4>

        <p class="text-justify">Com seu modulo registrado, ou utilizando o modulo de exemplo <strong>Application</strong>, é muito simples criar um novo controller, basta criar o mesmo no diretório <strong>Controller</strong> do seu modulo e extender de <strong>MVS\WorksenaMvc\AbstractActionController.</strong></p>
        <pre class="language-php">
            <code class="language-php">
                &lt;?php

                namespace SeuModulo\Controller;

                use MVS\WorksenaMvc\AbstractActionController;

                class IndexController extends AbstractActionController
                {
                    public function index()
                    {
                        return $this->render("seumodulo.index");
                    }
                }
            </code>
        </pre>

        <div class="line"></div>

        <h4 id="instalacao">Passando parâmetros para a <strong>view</strong></h4>
        <p class="text-justify">Caso deseje passar valores para a sua view, realize procedimento via array como mostrado no exemplo abaixo, sendo assim cada indice do array se transformará em uma variável na sua view.</p>
        <pre class="language-php">
            <code class="language-php">
                &lt;?php

                namespace SeuModulo\Controller;

                use MVS\WorksenaMvc\AbstractActionController;

                class IndexController extends AbstractActionController
                {
                    public function index()
                    {
                        return $this->render("seumodulo.index", [
                            'nome' => 'Walderlan Sena'
                        ]);
                    }
                }
            </code>
        </pre>

        <div class="col-md-12">
            <div class="line"></div>
            <p class="text-center">Feito com muito <i class="fas fa-heart text-danger"></i> Worksena</p>
            <br>
            <p class="text-center">Apoio -  <a href="https://www.mentesvirtuaissena.com" target="_blank">Mentes Virtuais Sena</a></p>
        </div>
    </div>
</div>
<script src="/assets/js/prism.js"></script>
