<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="/assets/css/bar.css">
<link rel="stylesheet" href="/assets/css/prism.css">

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header"></div>
        <ul class="list-unstyled components">
            <p class="text-center">Documentação</p>
            <li>
                <a href="/documentacao">Instalação</a>
            </li>
            <li class="active">
                <a href="/documentacao/modulos">Modulos</a>
            </li>
            <li>
                <a href="/documentacao/rotas">Rotas</a>
            </li>
            <li>
                <a href="/documentacao/controller">Controller</a>
            </li>
            <li>
                <a href="/documentacao/injecao-de-dependencia">Injeção de Dependência</a>
            </li>
            <li>
                <a href="/documentacao/views">Views</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Componentes</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Worksena-Authetication</a>
                    </li>
                    <li>
                        <a href="#">Worksena-orm</a>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="https://github.com/WalderlanSena/worksena" target="_blank" class="download"><i class="fab fa-github-alt"></i> Código fonte</a>
            </li>
            <li>
                <a href="https://pag.ae/bfr49JT" target="_blank" class="article"><i class="fas fa-hand-holding-usd"></i> Fazer uma Doação</a>
            </li>
        </ul>
        <p class="text-center"><strong>License - </strong> MIT</p>
        <p class="text-center cita">"A vida não te paga pelo que você sabe, e sim pelo que leva as pessoas a fazerem com que o você sabe!"</p>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <p class="text-lg-right">
            <button class="btn btn-sm btn-outline-danger mr-5" id="sidebarCollapse"><i class="fas fa-bars"></i> Documentação Menu</button>
        </p>

        <h1 class="text-danger"><i class="fas fa-download"></i> Criando um novo Modulo</h1>
        <div class="line"></div>
        <p class="text-justify">Para criar um novo modulo para a sua aplicação é muito simples, pasta criar um diretório dentro da pasta <strong>module</strong> e registrar o <strong>autoload</strong> do mesmo no <strong>composer.</strong></p>
        <pre class="language-shell">
            <code class="language-shell">
                ├── module
                │   └── SeuModulo
                │       ├── src
                │       │   ├── Controller
                │       │   ├── Repository
                │       │   └── Service
                │       └── view
                │           └── seumodulo
            </code>
        </pre>
        <p>Registrando no <strong>composer.json</strong>, após o registro execute o comando <strong>composer dump</strong></p>
        <pre class="language-php">
            <code class="language-php">
                {
                    "autoload": {
                          "psr-4": {
                            "Config\\": "config/",
                            "Application\\": "module/Application/src",
                            "SeuModulo\\": "module/SeuModulo/src"
                          }
                    }
                }
            </code>
        </pre>
    </div>
</div>
<script src="/assets/js/prism.js"></script>


