<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="/assets/css/bar.css">
<link rel="stylesheet" href="/assets/css/prism.css">

<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header"></div>
        <ul class="list-unstyled components">
            <p class="text-center">Documentação</p>
            <li>
                <a href="/documentacao">Instalação</a>
            </li>
            <li>
                <a href="/documentacao/modulo">Modulos</a>
            </li>
            <li class="active">
                <a href="/documentacao/rotas">Rotas</a>
            </li>
            <li>
                <a href="/documentacao/controller">Controller</a>
            </li>
            <li>
                <a href="/documentacao/injecao-de-dependencia">Injeção de Dependência</a>
            </li>
            <li>
                <a href="/documentacao/views">Views</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Componentes</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Worksena-Authetication</a>
                    </li>
                    <li>
                        <a href="#">Worksena-orm</a>
                    </li>
                    <li>
                        <a href="#">Worksena-validator</a>
                    </li>
                </ul>
            </li>
        </ul>

        <ul class="list-unstyled CTAs">
            <li>
                <a href="https://github.com/WalderlanSena/worksena" target="_blank" class="download"><i class="fab fa-github-alt"></i> Código fonte</a>
            </li>
            <li>
                <a href="https://pag.ae/bfr49JT" target="_blank" class="article"><i class="fas fa-hand-holding-usd"></i> Fazer uma Doação</a>
            </li>
        </ul>
        <p class="text-center"><strong>License - </strong> MIT</p>
        <p class="text-center cita">"A vida não te paga pelo que você sabe, e sim pelo que leva as pessoas a fazerem com que o você sabe!"</p>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <p class="text-lg-right">
            <button class="btn btn-sm btn-outline-danger mr-5" id="sidebarCollapse"><i class="fas fa-bars"></i> Documentação Menu</button>
        </p>

        <h1 class="text-danger"><i class="fas fa-download"></i> Configurando rotas da aplicação</h1>
        <div class="line"></div>

        <h4 id="instalacao">Adicionando rotas</h4>

        <p class="text-justify">Para criar uma nova rota na aplicação você deve ir no diretório <strong>config/routes</strong> e criar ou utilizar o arquivo de rotas já existênte com a seguite estrutura.</p>
        <pre class="language-php">
            <code class="language-php">
                &lt;?php

                namespace Config\Router;

                use Application\Controller\ApplicationController;

                return [
                    'home' => [
                        'method'        => 'GET',
                        'route'         => '/sua-rota',
                        'controller'    =>  ApplicationController::class,
                        'action'        => 'index',
                    ],
                ];
            </code>
        </pre>
        <p class="text-justify"> Dentro do diretório <strong>config/routes</strong> você pode criar diversos arquivos de definição de rotas, sendo uma boa prática nomeá-los os mesmos com a terminação <strong>nomedoarquivo.router.php</strong></p>

        <div class="col-md-12">
            <div class="line"></div>
            <p class="text-center">Feito com muito <i class="fas fa-heart text-danger"></i> Worksena</p>
            <br>
            <p class="text-center">Apoio -  <a href="https://www.mentesvirtuaissena.com" target="_blank">Mentes Virtuais Sena</a></p>
        </div>
    </div>
</div>
<script src="/assets/js/prism.js"></script>
